export const horizontalCardEventData = [
    {
        eventID: 'EVE789734',
        imageUrl: "/cardbanner.png",
        title: "House Of Chapora & Tweak Music Presents – Tim Taste Live",
        location: "New York, NY",
        date: "December 6th 2024",
        status: "Active",
        totalSeats: 200,
        reserved: 150,
        couponCount: 30,
        createdOn: "December 6th 2024"
    },
    {
        eventID: 'EVE789734',
        imageUrl: "/cardbanner.png",
        title: "House Of Chapora & Tweak Music Presents – Tim Taste Live",
        location: "Los Angeles, CA",
        date: "December 6th 2024",
        status: "Inactive",
        totalSeats: 100,
        reserved: 60,
        couponCount: 10,
        createdOn: "December 6th 2024"
    },
    {
        eventID: 'EVE789734',
imageUrl: "/cardbanner.png",
        title: "House Of Chapora & Tweak Music Presents – Tim Taste Live",
        location: "San Francisco, CA",
        date: "December 6th 2024",
        status: "Active",
        totalSeats: 500,
        reserved: 450,
        couponCount: 50,
        createdOn: "December 6th 2024"
    },
    {
        eventID: 'EVE789734',
imageUrl: "/cardbanner.png",
        title: "House Of Chapora & Tweak Music Presents – Tim Taste Live",
        location: "Chicago, IL",
        date: "December 6th 2024",
        status: "Active",
        totalSeats: 50,
        reserved: 30,
        couponCount: 5,
        createdOn: "December 6th 2024"
    },
    {
        eventID: 'EVE789734',
imageUrl: "/cardbanner.png",
        title: "House Of Chapora & Tweak Music Presents – Tim Taste Live",
        location: "Austin, TX",
        date: "December 6th 2024",
        status: "Inactive",
        totalSeats: 80,
        reserved: 50,
        couponCount: 20,
        createdOn: "December 6th 2024"
    },
    {
        eventID: 'EVE789734',
imageUrl: "/cardbanner.png",
        title: "House Of Chapora & Tweak Music Presents – Tim Taste Live",
        location: "Seattle, WA",
        date: "December 6th 2024",
        status: "Active",
        totalSeats: 150,
        reserved: 120,
        couponCount: 25,
        createdOn: "December 6th 2024"
    },
    {
        eventID: 'EVE789734',
imageUrl: "/cardbanner.png",
        title: "House Of Chapora & Tweak Music Presents – Tim Taste Live",
        location: "Seattle, WA",
        date: "December 6th 2024",
        status: "Active",
        totalSeats: 150,
        reserved: 120,
        couponCount: 25,
        createdOn: "December 6th 2024"
    },
    {
        eventID: 'EVE789734',
imageUrl: "/cardbanner.png",
        title: "House Of Chapora & Tweak Music Presents – Tim Taste Live",
        location: "Seattle, WA",
        date: "December 6th 2024",
        status: "Active",
        totalSeats: 150,
        reserved: 120,
        couponCount: 25,
        createdOn: "December 6th 2024"
    },
    {
        eventID: 'EVE789734',
imageUrl: "/cardbanner.png",
        title: "House Of Chapora & Tweak Music Presents – Tim Taste Live",
        location: "Seattle, WA",
        date: "December 6th 2024",
        status: "Active",
        totalSeats: 150,
        reserved: 120,
        couponCount: 25,
        createdOn: "December 6th 2024"
    },
    {
        eventID: 'EVE789734',
imageUrl: "/cardbanner.png",
        title: "House Of Chapora & Tweak Music Presents – Tim Taste Live",
        location: "Seattle, WA",
        date: "December 6th 2024",
        status: "Active",
        totalSeats: 150,
        reserved: 120,
        couponCount: 25,
        createdOn: "December 6th 2024"
    }
];
